const escapeHtml = (value: string): string => value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!);

export function landingPage(baseUrl: string): string {
  const origin = escapeHtml(baseUrl);
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="Describe a source feed once. SourceFoundry keeps fresh, neutral candidates flowing." />
  <link rel="alternate" type="text/markdown" href="${origin}/agent.md" title="SourceFoundry agent guide" />
  <link rel="alternate" type="text/plain" href="${origin}/llms.txt" title="SourceFoundry LLM instructions" />
  <title>SourceFoundry — dependable source supply for agents</title>
  <style>
    :root { --ink:#131512; --paper:#f1eee6; --field:#fbfaf5; --acid:#d8ff43; --sky:#c9dbff; --rust:#ca4b20; --quiet:#696a62; --hair:#bbb9af; }
    * { box-sizing:border-box } html { scroll-behavior:smooth } body { margin:0; color:var(--ink); background:var(--paper); font-family:ui-monospace,SFMono-Regular,Menlo,monospace; }
    body:before { content:""; position:fixed; inset:0; pointer-events:none; opacity:.18; background-image:radial-gradient(#4b4b45 .55px,transparent .55px); background-size:5px 5px; mix-blend-mode:multiply; } a { color:inherit; text-decoration-thickness:1px; text-underline-offset:3px } main { width:min(1180px,calc(100% - 40px)); margin:auto; }
    .nav { height:78px; display:flex; align-items:center; justify-content:space-between; border-bottom:1px solid var(--ink); position:relative; z-index:1; } .wordmark { font-size:21px; font-weight:900; letter-spacing:-.08em; text-decoration:none; } .nav-meta { display:flex; align-items:center; gap:20px; font-size:11px; text-transform:uppercase; letter-spacing:.08em; } .nav-meta a { text-decoration:none; border-bottom:1px solid var(--ink) }
    .hero { padding:83px 0 38px; display:grid; grid-template-columns:1fr 314px; gap:54px; border-bottom:1px solid var(--ink); position:relative; z-index:1; } .kicker { font-size:11px; text-transform:uppercase; letter-spacing:.12em; color:var(--rust); font-weight:800; } h1 { max-width:800px; margin:14px 0 26px; font:500 clamp(55px,8.1vw,108px)/.84 Georgia,serif; letter-spacing:-.08em; } .thesis { max-width:625px; margin:0; font:20px/1.42 Georgia,serif; } .hero-actions { display:flex; gap:18px; align-items:center; margin-top:30px; font-size:13px; } .button { display:inline-block; background:var(--acid); border:1px solid var(--ink); padding:13px 16px; text-decoration:none; font-weight:800; box-shadow:4px 4px 0 var(--ink); transition:transform .18s,box-shadow .18s; } .button:hover { transform:translate(2px,2px); box-shadow:2px 2px 0 var(--ink) }
    .promise { align-self:end; border:1px solid var(--ink); background:var(--sky); padding:18px; box-shadow:5px 5px 0 var(--ink); } .promise code { display:block; margin:13px 0; padding:11px; background:var(--ink); color:#f7f3e9; font-size:11px; line-height:1.5; overflow-wrap:anywhere; } .small { font-size:11px; line-height:1.55; color:var(--quiet) } .promise .small { color:#262a25 }
    .manifest { display:grid; grid-template-columns:190px 1fr; gap:30px; padding:27px 0; border-bottom:1px solid var(--ink); position:relative; z-index:1; } .manifest-title { font:500 28px/.96 Georgia,serif; letter-spacing:-.05em; } .lanes { display:grid; grid-template-columns:repeat(3,1fr); gap:1px; background:var(--ink); border:1px solid var(--ink); } .lane { min-height:120px; background:var(--field); padding:15px; } .lane:nth-child(2) { background:var(--acid) } .lane-label { display:block; color:var(--rust); font-size:10px; font-weight:bold; text-transform:uppercase; letter-spacing:.08em; margin-bottom:27px; } .lane strong { font:500 20px/1 Georgia,serif; letter-spacing:-.04em; }
    .case { display:grid; grid-template-columns:.87fr 1.13fr; gap:54px; padding:78px 0; border-bottom:1px solid var(--ink); position:relative; z-index:1; } h2 { font:500 clamp(38px,5vw,66px)/.9 Georgia,serif; letter-spacing:-.07em; margin:11px 0 20px; } .case-copy { max-width:490px; font:17px/1.5 Georgia,serif; } .policy { background:var(--ink); color:#f6f1e7; padding:22px; border:1px solid var(--ink); box-shadow:7px 7px 0 var(--rust); } .policy-top { display:flex; justify-content:space-between; font-size:10px; text-transform:uppercase; letter-spacing:.08em; color:#a8b19d; } .policy pre { margin:20px 0 0; white-space:pre-wrap; font:13px/1.58 ui-monospace,SFMono-Regular,Menlo,monospace; color:#f6f1e7; } .policy .key { color:var(--acid) } .policy .value { color:var(--sky) }
    .economics { display:grid; grid-template-columns:repeat(3,1fr); border-bottom:1px solid var(--ink); position:relative; z-index:1; } .economic { padding:25px 23px 31px 0; min-height:220px; } .economic + .economic { padding-left:23px; border-left:1px solid var(--ink); } .economic b { display:block; margin:28px 0 8px; font:500 29px/.95 Georgia,serif; letter-spacing:-.05em; } .number { color:var(--rust); font-size:11px; letter-spacing:.08em; }
    .start { display:grid; grid-template-columns:.8fr 1.2fr; gap:54px; padding:78px 0; position:relative; z-index:1; } form { background:var(--field); border:1px solid var(--ink); padding:22px; } label { display:block; margin-top:16px; font-size:10px; text-transform:uppercase; letter-spacing:.1em; } input { width:100%; padding:11px 0 8px; border:0; border-bottom:1px solid var(--ink); outline:0; background:transparent; color:var(--ink); font:15px ui-monospace,SFMono-Regular,Menlo,monospace; } button { margin-top:26px; padding:13px 16px; cursor:pointer; border:1px solid var(--ink); background:var(--acid); color:var(--ink); box-shadow:4px 4px 0 var(--ink); font:800 12px ui-monospace,SFMono-Regular,Menlo,monospace; } button:disabled { opacity:.55; cursor:wait; box-shadow:none; transform:translate(4px,4px) } #result { display:none; margin:20px 0 0; padding:14px; overflow-wrap:anywhere; white-space:pre-wrap; background:var(--ink); color:#f6f1e7; font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace; }
    .agent-card { border-top:1px solid var(--ink); padding-top:18px; margin-top:26px; } .agent-card p { max-width:460px; font:15px/1.5 Georgia,serif; } .copy { border:0; box-shadow:none; margin:0; padding:0; background:transparent; border-bottom:1px solid var(--ink); font-size:11px; } footer { display:flex; justify-content:space-between; gap:25px; border-top:1px solid var(--ink); padding:22px 0 32px; font-size:11px; position:relative; z-index:1; }
    @media (max-width:760px) { main { width:min(100% - 28px,1180px) } .nav-meta span { display:none } .hero,.case,.start { grid-template-columns:1fr; gap:33px; padding-top:53px; } .manifest { grid-template-columns:1fr; gap:15px; } .lanes,.economics { grid-template-columns:1fr; } .lane + .lane,.economic + .economic { border-left:0; border-top:1px solid var(--ink); padding-left:0; } .economic { min-height:0; padding:23px 0; } footer { flex-direction:column; } h1 { font-size:58px; } }
  </style>
</head>
<body>
  <main>
    <nav class="nav"><a class="wordmark" href="/">SOURCEFOUNDRY</a><div class="nav-meta"><span>Dependable source supply for agents</span><a href="${origin}/agent.md">Agent guide</a></div></nav>
    <section class="hero">
      <div><div class="kicker">A source foundry, not another answer engine</div><h1>Describe the supply.<br>Keep it flowing.</h1><p class="thesis">Tell SourceFoundry which feeds and bounded discovery lanes matter. It operates collection, deduplication, freshness, and source health while your product decides what the candidates mean.</p><div class="hero-actions"><a class="button" href="#start">Create an agent workspace ↓</a><a href="${origin}/openapi.json">Read the contract</a></div></div>
      <aside class="promise"><div class="kicker">Agent starts here</div><code>GET ${origin}/agent.md<br>POST ${origin}/v1/source-feeds<br>GET ${origin}/v1/source-feeds/{id}/candidates</code><p class="small">No dashboard required. One tenant-scoped credential builds a durable feed, runs it, and reads normalized candidates with provenance and health.</p></aside>
    </section>
    <section class="manifest"><div><div class="kicker">The job</div><div class="manifest-title">You describe the need. SourceFoundry keeps the supply moving.</div></div><div class="lanes"><div class="lane"><span class="lane-label">You control</span><strong>Supply contract</strong><p class="small">Exact feeds, bounded discovery, cadence, and exclusions.</p></div><div class="lane"><span class="lane-label">SourceFoundry does</span><strong>Collect + normalize</strong><p class="small">Scheduling, dedupe, provenance, retries, and source health.</p></div><div class="lane"><span class="lane-label">Your product owns</span><strong>Meaning</strong><p class="small">Judgment, ranking, writing, workflow, and publication.</p></div></div></section>
    <section class="case"><div><div class="kicker">A durable feed</div><h2>Describe the source supply once. Let every consumer use it differently.</h2><p class="case-copy">“Track Indian AI policy daily” should not make every agent independently operate feeds, search providers, retries, and deduplication. SourceFoundry supplies the same neutral candidates; a policy product, newsroom, or research agent can each apply its own judgment afterward.</p></div><div class="policy"><div class="policy-top"><span>Source feed / operated by SourceFoundry</span><span>stable candidate contract</span></div><pre>{
  <span class="key">"name"</span>: <span class="value">"Indian AI policy supply"</span>,
  <span class="key">"purpose"</span>: <span class="value">"Official policy changes and consequential reactions"</span>,
  <span class="key">"sources"</span>: [<span class="value">"official RSS"</span>, <span class="value">"bounded discovery"</span>],
  <span class="key">"cadence"</span>: { <span class="value">"everyMinutes": 720</span> },
  <span class="key">"output"</span>: <span class="value">"neutral candidates with provenance"</span>
}</pre></div>
    </section>
    <section class="economics"><div class="economic"><span class="number">01 / WHAT A CUSTOMER BUYS</span><b>Evidence capacity</b><p class="small">A plan includes a bounded number of active briefs and evidence runs—not exposed supplier keys or mysterious provider bills.</p></div><div class="economic"><span class="number">02 / WHAT YOU OPERATE</span><b>Approved source lanes</b><p class="small">SourceFoundry pays for infrastructure and only uses hosted providers where its commercial agreement permits that customer use. Normal fallback is part of the policy.</p></div><div class="economic"><span class="number">03 / HOW MARGIN SURVIVES</span><b>Policy limits</b><p class="small">Each run has a fixed source lane, cadence, result cap, and budget. Heavy, private, or non-approved sources use metered connectors or bring-your-own-key.</p></div></section>
    <section class="start" id="start"><div><div class="kicker">Start without a human</div><h2>Give an agent dependable source supply now.</h2><p class="case-copy">Create a bounded workspace and store the one-time token in the agent’s secret store. The agent can then build a durable feed from exact sources and bounded discovery, run it, and sync neutral candidates.</p><div class="agent-card"><div class="kicker">Prompt your agent can use</div><p>“Create a SourceFoundry workspace, securely store its credential, build a recurring source feed from the sources I describe, run it, and return neutral candidates with links, dates, provenance, and source health.”</p><button class="copy" id="copyPrompt" type="button">Copy agent prompt</button></div></div>
      <form id="enrollment"><div class="kicker">Create workspace</div><label for="slug">Workspace slug</label><input id="slug" name="slug" required minlength="3" pattern="[a-z0-9-]+" placeholder="market-intelligence" /><label for="name">Workspace name</label><input id="name" name="name" required placeholder="Market Intelligence" /><label for="agentLabel">Agent label</label><input id="agentLabel" name="agentLabel" required value="autonomous-agent" /><button id="submit" type="submit">Create credential + workspace</button><pre id="result" aria-live="polite"></pre></form>
    </section>
    <footer><span>Product of <a href="https://4agents.fyi">4agents.fyi</a></span><span><a href="${origin}/.well-known/sourcefoundry.json">Service descriptor</a> · <a href="${origin}/v1/meta">Capabilities</a></span></footer>
  </main>
  <script>
    const form = document.querySelector('#enrollment'); const result = document.querySelector('#result'); const submit = document.querySelector('#submit');
    document.querySelector('#copyPrompt').addEventListener('click', async () => { const prompt = 'Create a SourceFoundry workspace, securely store its credential, build a recurring source feed from the sources I describe, run it, and return neutral candidates with links, dates, provenance, and source health.'; await navigator.clipboard.writeText(prompt); document.querySelector('#copyPrompt').textContent = 'Copied'; });
    form.addEventListener('submit', async (event) => { event.preventDefault(); submit.disabled = true; result.style.display = 'block'; result.textContent = 'Creating your workspace…';
      try { const response = await fetch('/v1/agent-enrollments', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify(Object.fromEntries(new FormData(form))) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || 'Enrollment failed');
        result.textContent = '# Store this secret now — it is not shown again\\nSOURCEFOUNDRY_URL=' + body.baseUrl + '\\nSOURCEFOUNDRY_API_TOKEN=' + body.token + '\\nSOURCEFOUNDRY_TENANT_ID=' + body.tenant.id + '\\n\\n# Next: POST /v1/source-feeds with an Idempotency-Key\\n# Contract: ' + body.next.openapi;
      } catch (error) { result.textContent = 'Could not create workspace: ' + error.message; } finally { submit.disabled = false; }
    });
  </script>
</body>
</html>`;
}
